version: "3.8"
services:
  queue:
    container_name: ${DOCKER_APP_CONTAINER_NAME}-queue
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - cache
      - db
      - composer
    networks:
      - proxynet
  db:
    container_name: ${DOCKER_APP_CONTAINER_NAME}-db
    platform: linux/x86_64
    image: mysql:8.0
    restart: "no"
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_EXPOSED_DB_PORT}:3306
    volumes:
      - db_data_portal:/var/lib/mysql
    networks:
      - proxynet
    env_file:
      - .env
  cache:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: ${DOCKER_APP_CONTAINER_NAME}-cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    image: redis:5.0
    ports:
      - 6379
    volumes:
      - cache_data_portal:/data
    networks:
      - proxynet
  nginx:
    image: nginx:stable-alpine
    container_name: ${DOCKER_APP_CONTAINER_NAME}-nginx
    ports:
      - ${DOCKER_EXPOSED_NGINX_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.temp
    depends_on:
      - composer
      - db
      - cache
    command: /bin/sh -c "envsubst '$$DOCKER_NGINX_LOCAL_IP $$DOCKER_APP_CONTAINER_NAME' < /etc/nginx/conf.d/default.temp > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    env_file:
      - .env
    networks:
      - proxynet
  php-fpm:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile.PHP-FPM
    container_name: ${DOCKER_APP_CONTAINER_NAME}-php-fpm
    volumes:
      - ./.docker/xdebug-nginx.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./:/var/www/html
    ports:
      - 9000
    depends_on:
      - composer
      - db
      - cache
    networks:
      - proxynet
  composer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_APP_CONTAINER_NAME}-composer
    volumes:
      - .:/app
    command: composer install
    networks:
      - proxynet
    env_file:
      - .env

volumes:
  db_data_portal:
    driver: "local"
  cache_data_portal:
    driver: "local"

networks:
  proxynet:
    name: portal
